### ISSUE TITLE
Not sure where "Gloopy" is

### ISSUE THREAD

**Issue by stuaxo** [tartley/gloopy#1]
In the examples there is "from gloopy import Gloopy" but this doesn't work, I can't work out where "Gloopy" (upper case G) is defined.

**Comment by tartley** [comment]
Hey. My apologies. This codebase is old and not well maintained, especially the examples, sorry!

I think I must have refactored the 'Gloopy' class away, and not updated the examples.

The only example that I know ran for me recently is the one called 'browser.py'

**Comment by tartley** [comment]
...and, come to think of it, 'browser.py' displays a blank (colored) screen until you start pressing keys.

The keys are listed in the source, here:
https://github.com/tartley/gloopy/blob/master/gloopy/examples/browser.py#L247

generally they follow the convention:
1 2 3 4 5 6 7 - insert different simple 3d shapes
q w e r t y u - insert modest compound shapes (eg. small groups of cubes)
z x c v b - insert larger compound shapes

backspace - remove a shape
up / down or pageup/pagedown - move orbitting camera closer / further away

Then you can modify existing (simple, not compound) shapes:
space = - 0 delete   select different groups of faces. Only works on simple objects, if memory serves, not compound ones.
then after selecting faces, use the keys_ctrl to extrude faces, subdivide faces, etc.

eg.
* make a cube
* space to highlight all faces I think
* ctrl-W to extrude all faces, making a 3d cross shape)
* use =/- to select just the endmost faces of the cross 
* ctrl-O to 'stellate' those faces (making little pyramids on the ends of the cross
* =/- to select just the faces of those pyramids
* ctrl-W again to extrude those faces
and repeat.

Vary the result by choosing different initial shapes, different extrusion lengths, and different angles of stellation.

**Comment by tartley** [comment]
I'm running it on Ubuntu. Under Python3.6 I believe. Running it elsewhere is less likely to work.

**Comment by tartley** [comment]
and, you should be aware, the code is quite messy. But, for all that, a lot of work went into it and I'm still quite proud of some aspects of it. I think the inner render loop is pretty reasonable, for what it is (ie. a series of glDrawElements calls, one per independently positioned/oriented entity.) There are a couple of small optimisations you could do to improve that render loop:

1. you could combine the glTranslate and glMultMatrix into a single glMultMatrix call, if you did a bit of extra math to merge the translation into the matrix. The number of gl function calls is a bottleneck, so that would probably speed things up.

2. If drawing more than one of the same thing, you don't have to call glBindVertexArray inbetween rendering each one. You would group glyphs by their vertexlist, so that *all* glyphs of the same type get drawn consecutively.

**Comment by tartley** [comment]
Having said that, if I were to get heavily into it again, I'd really want to investigate an alternative renderloop, in which position/orientations for all entities were passed to the GPU as one big array, each frame, and those matrices were applied to the entity vertices by shaders. That means you could then render every object in the world using a single glDrawElements call, and not need any "loop" in you render loop. This would eliminate the "calling gl functions" bottleneck entirely, and would produce a Python graphics engine that was just as fast, or moreso, than hobbyist ones written in C. Is my theory, anyway. :-)

**Comment by tartley** [comment]
I'm rambling, aren't I?

**Comment by stuaxo** [comment]
Possibly rambling, but it all makes sense :) especially drawing as few calls as possible.

I'm pretty glacial in hobbyist graphics dev myself, I always end up back at your page, the way of drawing shapes is the about the only one I've seen that feels close to a sane way of doing things.

I've kind of got stuck in infrastructure - I'm frustrated that everything doesn't work together easily (GUI toolkits, various pyGLs etc) .. maybe once I fix some of these things I'll build something.

As an alternative way of doing shapes, I just found out about how Wings3D does things, it uses a "Winged Edge structure", which allows various manipulations  https://pages.mtu.edu/~shene/COURSES/cs3621/NOTES/model/winged-e.html

**Comment by stuaxo** [comment]
It's fun running the browser app, I wonder why there is a short pause between pressing Z and them appearing ?

Recovered an ancient version of Gloopy from pypi, it looks like it ended up as mainloop -

https://gist.github.com/stuaxo/1fd607780a5b50a055b8776ad307080f

**Comment by tartley** [comment]
Ah, that pause is because the operation to create all the vertices is quite slow.

It's doing all the math and twiddling to actually generate the vertices/colors/normals, then converting those Python floats into ctype floats in arrays, plus then shunting that geometry over to the graphics card. There's lots that could be optimised here - this was definitely 'first attempt' code.

In a game or somesuch, you might consider pre-generating all the geometries you could at start-up, to minimise horrid pauses later while aniumating.

Also, I suspect I could rework the code using cffi (or maybe ctypes could do it) so that my Python shape classes store their vertices directly in a pre-existing ctypes array, thus negating the need to do the expensive conversion from Python types to ctypes arrays.

Also, one could probably fork off the generation of these geometries asynchronously, using processes, threads, or maybe even python's new async? Then keep animating smoothly while that churns in the background, and add the resulting glyph into the world when it's done.

**Comment by tartley** [comment]
Thanks for the link to Wing stuff - I'm interested to read that.

As it happens, I started writing some graphics code again this week, for the first time in 5 years (I became a Dad, and then have also been quite ill the last couple of years, so haven't had much time or energy for it.)

I'm starting with something modest, the simplest 2D game I can think of, using pyglet. See if I can finish it and produce a downloadable executable that doesn't require python, etc to be pre-installed.
